### ISSUE TITLE
not network connection (yml file change)

### ISSUE THREAD

**Issue by nps798** [abhitatachar2000/dockerize-chromadb#1]
Hi, thanks for sharing the dockerize chromadb setting
I faced connection time out error when I compose your docker file

I figured out and succeed by add the Dockerfile a line
network: host

so the file become...
version: "3.0"
services:
  application:
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
...

**Comment by abhitatachar2000** [comment]
Hey Lin,

Thanks for noticing this. 

There is a bridge network that I had already configured (by the name 'net') in the docker-compose (Line 30 in docker-compose). The same network is used by both the services - chroma and the application (Check lines 11 and 20). 

And that works fine ( I just checked it out). 

I'm adding a screenshot below for you to look over. 
![image](https://github.com/abhitatachar2000/dockerize-chromadb/assets/66842711/6206cb44-3b9d-4610-a11d-37686690366b)

However, I am glad that the change worked for you! Thanks again for noticing that issue and also for coming up and sharing the alternative solution.

Best regards,
Abhi.
